version: 2
jobs:
  build:
    working_directory: ~/ledgers.js
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          shell: /bin/sh
          command: |
            docker run -d -v ~/ledgers.js/:/app --name=app buildkite/puppeteer:v1.10.0 /bin/sh -c 'sleep 999'
      - run:
          shell: /bin/sh
          command: sleep 10
      - run:
          shell: /bin/sh
          command: docker exec app /bin/sh -c 'cd /app; npm install -g npm@latest'
      - run:
          shell: /bin/sh
          command: |
            apt-get -y update
            apt-get -y install build-essential
      - run:
          shell: /bin/sh
          command: docker exec app /bin/sh -c 'cd /app; npm install'
      - run:
          shell: /bin/sh
          command: docker exec app /bin/sh -c 'cd /app; npm install puppeteer --unsafe-perm=true --allow-root'
      - run:
          shell: /bin/sh
          command: docker exec app /bin/sh -c 'cd /app; npm run all'
      - run:
          shell: /bin/sh
          command: docker exec app /bin/sh -c 'cd /app; npm run test-report'
      - store_test_results:
          path: ./test-report
      - store_artifacts:
          path: ./test-report